// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhlkvbdbmadenoplvocn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhobGt2YmRibWFkZW5vcGx2b2NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0Mzk3ODIsImV4cCI6MjA3MDAxNTc4Mn0.F0q1Bo4tPhwtfcxrPF8WrhhCwxgl3Dcpd8o20H_zJ_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});